# -*- coding: utf-8 -*-
"""DirectingStocksData.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1I_AETL_rZjWKmXK5XSh711y7ioMm4hFi
"""

pip install bsedata

from bsedata.bse import BSE

b=BSE()

print(b)

q = b.getQuote('534976')
q

codelist = ["500116", "512573"]

for code in codelist:
  quote = b.getQuote(code)
  print(quote["companyName"])
  print(quote["currentValue"])
  print(quote["updatedOn"])

b.topGainers()

b.topLosers()